# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-11 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='imgs/')),
            ],
            options={
                'db_table': 'stupic',
            },
        ),
    ]
